# Generated by Django 4.2.8 on 2023-12-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataGrapeJs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grapejs', to='flatpages.flatpage')),
            ],
        ),
    ]
