# Generated by Django 4.2.8 on 2023-12-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_datagrapejs_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='datagrapejs',
            name='css',
            field=models.TextField(blank=True, null=True, verbose_name='css'),
        ),
        migrations.AddField(
            model_name='datagrapejs',
            name='js',
            field=models.TextField(blank=True, null=True, verbose_name='js'),
        ),
    ]
